---
- name: Install supervisor
  apt:
    name: supervisor
    state: latest

- name: Copy supervisor conf
  copy:
    src: supervisor.conf
    dest: /etc/supervisor/supervisord.conf

- name: Copy supervisor script
  copy:
    src: entrypoint.sh
    dest: /opt/entrypoint.sh
    mode: 0744
